group: build
steps:
  - name: build
    label: ":tapioca: build: anyscale py{{matrix}} docker"
    tags:
      - python_dependencies
      - docker
      - core_cpp
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- anyscale --python-version {{matrix}}
        --platform cu12.1.1 --platform cpu --image-type ray
    depends_on:
      - manylinux
      - forge
      - raycudabase
      - raycpubase
    job_env: forge
    matrix:
      - "3.8"
      - "3.9"
      - "3.11"

  - name: build
    label: ":tapioca: build: anyscale-ml py{{matrix}} docker"
    tags:
      - python_dependencies
      - docker
      - core_cpp
    instance_type: medium
    commands:
      - bazel run //ci/ray_ci:build_in_docker -- anyscale --python-version {{matrix}}
        --platform cu11.8.0 --image-type ray-ml
    depends_on:
      - manylinux
      - forge
      - ray-mlcudabase
    job_env: forge
    matrix:
      - "3.8"
      - "3.9"
