#ci:group=Large GPU tests

- label: ":tv: :book: Doc GPU tests and examples"
  conditions:
    ["NO_WHEELS_REQUIRED", "RAY_CI_PYTHON_AFFECTED", "RAY_CI_TUNE_AFFECTED", "RAY_CI_DOC_AFFECTED"]
  commands:
    - cleanup() { if [ "${BUILDKITE_PULL_REQUEST}" = "false" ]; then ./ci/build/upload_build_info.sh; fi }; trap cleanup EXIT
    - DOC_TESTING=1 TRAIN_TESTING=1 TUNE_TESTING=1 ./ci/env/install-dependencies.sh
    - pip install -Ur ./python/requirements/ml/dl-gpu-requirements.txt
    - ./ci/env/env_info.sh
    # Test examples with newer version of `transformers`
    # TODO(amogkam): Remove when https://github.com/ray-project/ray/issues/36011
    # is resolved.
    - pip install -U transformers
    - bazel test --config=ci $(./ci/run/bazel_export_options) --build_tests_only --test_tag_filters=gpu,-timeseries_libs,-post_wheel_build,-doctest,-team:ml 
      doc/...

- label: ":book: Doctest (GPU)"
  commands:
    - cleanup() { if [ "${BUILDKITE_PULL_REQUEST}" = "false" ]; then ./ci/build/upload_build_info.sh; fi }; trap cleanup EXIT
    - DOC_TESTING=1 TRAIN_TESTING=1 TUNE_TESTING=1 ./ci/env/install-dependencies.sh
    - pip install -Ur ./python/requirements/ml/dl-gpu-requirements.txt
    - ./ci/env/install-horovod.sh
    # Test examples with newer version of `transformers`
    # TODO(amogkam): Remove when https://github.com/ray-project/ray/issues/36011 
    # is resolved.
    # TODO(scottjlee): Move datasets to train/data-test-requirements.txt 
    # (see https://github.com/ray-project/ray/pull/38432/)
    - pip install transformers==4.30.2 datasets==2.14.0
    - ./ci/env/env_info.sh
    - bazel test --config=ci $(./scripts/bazel_export_options)
      --test_tag_filters=doctest,-cpu
      python/ray/... doc/...
