#ci:group=:ferris_wheel: Wheels and containers

- label: ":ferris_wheel: Debug Wheels"
  conditions:
    [
        "RAY_CI_LINUX_WHEELS_AFFECTED",
        "RAY_CI_JAVA_AFFECTED",
    ]
  instance_size: medium
  commands:
    # Build the debug wheels
    - RAY_DEBUG_BUILD=debug LINUX_WHEELS=1 ./ci/ci.sh build
    # Upload the wheels.
    # We don't want to push on PRs, in fact, the copy_files will fail because unauthenticated.
    - if [ "$BUILDKITE_PULL_REQUEST" != "false" ]; then exit 0; fi
    - pip install -q docker aws_requests_auth boto3
    - ./ci/env/env_info.sh
    # Upload to branch directory.
    - python .buildkite/copy_files.py --destination branch_wheels --path ./.whl
    # Upload to latest directory.
    - if [ "$BUILDKITE_BRANCH" == "master" ]; then python .buildkite/copy_files.py --destination wheels --path ./.whl; fi
